export const mockDelegation = {
  country: "Uzbekistan",
  coordinator: {
    name: "Davron Tukhtaev",
    email: "toxtayev.davron@mail.ru",
    role: "National Coordinator",
    lastLogin: "2025-09-18 14:03:48",
  },
  participants: [
    {
      firstName: "Sunatullo",
      lastName: "Khojiev",
      role: "Team Leader",
      yearOfBirth: 1991,
      gender: "Male",
      tshirtSize: "L",
      dietary: "halal",
      passportNumber: "FA8475924",
    },
    {
      firstName: "Davron",
      lastName: "Tukhtaev",
      role: "Deputy Leader",
      yearOfBirth: 1992,
      gender: "Male",
      tshirtSize: "M",
      dietary: "halal",
      passportNumber: "FA8314757",
    },
    {
      firstName: "Sunnatov",
      lastName: "Asilbek",
      role: "Contestant",
      yearOfBirth: 2007,
      gender: "Male",
      tshirtSize: "M",
      dietary: "halal",
      passportNumber: "FA5818936",
    },
    {
      firstName: "Ulug'bek",
      lastName: "Rakhmatulaev",
      role: "Contestant",
      yearOfBirth: 2008,
      gender: "Male",
      tshirtSize: "M",
      dietary: "normal",
      passportNumber: "FA8774213",
    },
    {
      firstName: "Salimov",
      lastName: "Sardor",
      role: "Contestant",
      yearOfBirth: 2009,
      gender: "Male",
      tshirtSize: "M",
      dietary: "halal",
      passportNumber: "FA8543523",
    },
    {
      firstName: "Timur",
      lastName: "Kadirbergenov",
      role: "Contestant",
      yearOfBirth: 2008,
      gender: "Male",
      tshirtSize: "XL",
      dietary: "halal",
      passportNumber: "FA8511182",
    },
    {
      firstName: "Azamat",
      lastName: "Seydaliev",
      role: "IC Member",
      yearOfBirth: 2003,
      gender: "Male",
      tshirtSize: "M",
      dietary: "halal",
      passportNumber: "FA9216871",
    },
    {
      firstName: "Asadullo",
      lastName: "Ganiev",
      role: "ISC Member",
      yearOfBirth: 2001,
      gender: "Male",
      tshirtSize: "L",
      dietary: "normal",
      passportNumber: "FA1924371",
    },
    {
      firstName: "Davlatbek",
      lastName: "Mirokilov",
      role: "ITC Member",
      yearOfBirth: 2004,
      gender: "Male",
      tshirtSize: "XL",
      dietary: "normal",
      passportNumber: "FA6881470",
    },
    {
      firstName: "Ilkhom",
      lastName: "Sattarov",
      role: "Guest",
      yearOfBirth: 1985,
      gender: "Male",
      tshirtSize: "L",
      dietary: "halal",
      passportNumber: "FA8401811",
    },
  ],
}

export const mockTravelInfo = {
  arrivals: [
    {
      date: "25 Jul 2025",
      time: "17:10",
      location: "Sucre Airport (SRE)",
      flight: "QB584",
      members: [
        "Sunatullo Khojiev",
        "Davron Tukhtaev",
        "Sunnatov Asilbek",
        "Ulug'bek Rakhmatulaev",
        "Salimov Sardor",
        "Timur Kadirbergenov",
        "Turaboy Shermatov",
      ],
    },
  ],
  departures: [
    {
      date: "04 Aug 2025",
      time: "15:00",
      location: "Sucre Airport (SRE)",
      flight: "QB583",
      members: ["Nodirbek Barnaev"],
    },
    {
      date: "04 Aug 2025",
      time: "17:45",
      location: "Sucre Airport (SRE)",
      flight: "QB585",
      members: [
        "Sunatullo Khojiev",
        "Davron Tukhtaev",
        "Sunnatov Asilbek",
        "Ulug'bek Rakhmatulaev",
        "Salimov Sardor",
        "Timur Kadirbergenov",
        "Turaboy Shermatov",
      ],
    },
    {
      date: "04 Aug 2025",
      time: "17:45",
      location: "Sucre Airport (SRE)",
      flight: "QB585",
      members: ["Azamat Seydaliev", "Erkin Kurbonov", "Saidmurod Abdujabborov", "Jamshid Khudayberdiev"],
    },
    {
      date: "04 Aug 2025",
      time: "17:45",
      location: "Sucre Airport (SRE)",
      flight: "QB585",
      members: ["Davlatbek Mirokilov"],
    },
    {
      date: "04 Aug 2025",
      time: "17:45",
      location: "Sucre Airport (SRE)",
      flight: "QB585",
      members: ["Asadullo Ganiev"],
    },
  ],
}
